# Generated by Django 3.0.2 on 2020-02-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assign_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('assign_name', models.CharField(max_length=50)),
                ('teacher_email', models.CharField(max_length=50)),
                ('c_id', models.CharField(max_length=10)),
                ('initial_date', models.DateTimeField()),
                ('assign_due_date', models.DateTimeField()),
                ('assign_max_size_kb', models.IntegerField()),
            ],
        ),
    ]
