# Generated by Django 3.0.2 on 2020-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAssignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
