# Generated by Django 3.0.2 on 2020-03-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAssignments', '0002_auto_20200312_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assign_file',
            field=models.FileField(default=None, upload_to='files/'),
            preserve_default=False,
        ),
    ]
