# Generated by Django 3.0.2 on 2020-03-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageAssignments', '0003_assignment_assign_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assign_file',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
