# Generated by Django 3.0.2 on 2020-03-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageAssignments', '0006_auto_20200315_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assign_file',
        ),
    ]
