# Generated by Django 3.0.2 on 2020-02-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_id', models.CharField(max_length=10)),
                ('student_email', models.CharField(max_length=50)),
                ('submission_date', models.DateTimeField()),
                ('submission_file_name', models.CharField(max_length=50)),
                ('submission_marks_logic', models.BooleanField(max_length=6)),
                ('submission_marks_uniqueness', models.BooleanField(max_length=6)),
                ('submission_marks_quality', models.BooleanField(max_length=6)),
            ],
            options={
                'unique_together': {('assign_id', 'student_email')},
            },
        ),
    ]
