# Generated by Django 3.0.2 on 2020-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageSubmissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_file_name',
            field=models.FileField(max_length=50, upload_to=''),
        ),
    ]
