# Generated by Django 3.0.2 on 2020-03-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageSubmissions', '0002_auto_20200312_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_file_name',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_marks_logic',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_marks_quality',
            field=models.IntegerField(max_length=6),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_marks_uniqueness',
            field=models.IntegerField(max_length=6),
        ),
    ]
