# Generated by Django 3.0.2 on 2020-03-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageSubmissions', '0003_auto_20200315_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_marks_logic',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_marks_quality',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_marks_uniqueness',
            field=models.IntegerField(),
        ),
    ]
