# Generated by Django 3.0.2 on 2020-02-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assign_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('assign_name', models.CharField(max_length=50)),
                ('teach_email', models.CharField(max_length=50)),
                ('c_id', models.CharField(max_length=10)),
                ('initial_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('max_size_kb', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('c_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=20)),
                ('c_credit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(verbose_name='date published')),
                ('semester', models.IntegerField()),
                ('course', models.CharField(max_length=10)),
                ('stu_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=15)),
                ('id_no', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='stu_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(verbose_name='date published')),
                ('course', models.CharField(max_length=10)),
                ('teach_email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=15)),
                ('id_no', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='teacher_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_id', models.CharField(max_length=10)),
                ('stu_email', models.CharField(max_length=50)),
                ('subm_date', models.DateTimeField()),
                ('file_name', models.CharField(max_length=50)),
                ('marks_logic', models.BooleanField(max_length=6)),
                ('marks_uniqueness', models.BooleanField(max_length=6)),
                ('marks_quality', models.BooleanField(max_length=6)),
            ],
            options={
                'unique_together': {('assign_id', 'stu_email')},
            },
        ),
    ]
